### PR TITLE
Use temporary file to store temporary things

### LINKED ISSUE #103: Required or recommended to have cosign.pub?
When signing something, you mention that it is recommended to have a cosign.pub. This is fine, but I don't have one in the repository which I'm testing. 
I try to set mine using the environment variable ``COSIGN_PUBLIC_KEY``.

**Problem:**
```Finished getting docker digest and tags
============================================================================================
Signing image
Sign image
Pushing signature to: ghcr.io/something
Verify signing
Error: loading public key: open cosign.pub: no such file or directory
main.go:46: error during command execution: loading public key: open cosign.pub: no such file or director
```
It does not seem to find a cosign.pub even though I added the environment variable.

**Assumption:**
I expect the software to check if the environment variable is set, if it is, it should be used, if not, it will try to look for a cosign.pub in the directory. If neither are set or found, it should give me the above error.

### PR DESCRIPTION
**Pull request by JeroenKnoops**
Using `mktemp` to generate a temporary file

## Example run
https://github.com/philips-software/docker-tern/runs/5007515003?check_suite_focus=true

## Related issues
Closes #103, #99

### CODE REVIEW

File: container_digest.sh [hunk 1]
```diff
@@ -66,18 +66,22 @@ if [ -n "${SIGN}" ]
 then
   echo "Signing image"
 
+  COSIGN_KEY=$(mktemp /tmp/cosign.XXXXXXXXXX) || exit 1
```
Comment (bartgolsteijn) [inline container_digest.sh:69]: It seems like there is some code duplication in writing and removing the keys, what is the reason for not creating them at the top of the script and removing them at the end (outside of if-clauses)?

Comment (JeroenKnoops) [reply container_digest.sh:69]: Done!

**Review by bartgolsteijn — APPROVED** [review]
You are a great success!
